# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.lambdaNR <- function(G, maxIter, eps, verbose) {
    .Call(`_bayesEL_lambdaNR`, G, maxIter, eps, verbose)
}

.MeanReg_logEL <- function(y, X, beta, maxIter = 100L, eps = 1e-7) {
    .Call(`_bayesEL_MeanReg_logEL`, y, X, beta, maxIter, eps)
}

.QuantReg_logEL <- function(y, X, beta, alpha, maxIter = 100L, eps = 1e-7) {
    .Call(`_bayesEL_QuantReg_logEL`, y, X, beta, alpha, maxIter, eps)
}

