# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.evalEpsilonsLS <- function(y, X, Z, beta, gamma, sig2) {
    .Call(`_bayesEL_evalEpsilonsLS`, y, X, Z, beta, gamma, sig2)
}

.evalWeights <- function(deltas, omegas, epsilons) {
    .Call(`_bayesEL_evalWeights`, deltas, omegas, epsilons)
}

.lambdaNRC <- function(G, weights, maxIter, relTol, verbose) {
    .Call(`_bayesEL_lambdaNRC`, G, weights, maxIter, relTol, verbose)
}

.omega.hat.EM <- function(omegasInit, G, deltas, epsilons, maxIter, relTol, absTol, verbose) {
    .Call(`_bayesEL_omegaHatEM`, omegasInit, G, deltas, epsilons, maxIter, relTol, absTol, verbose)
}

.logELC <- function(omegas, epsilons, deltas) {
    .Call(`_bayesEL_logELC`, omegas, epsilons, deltas)
}

.ind.smooth <- function(x, s) {
    .Call(`_bayesEL_indSmooth`, x, s)
}

.evalPsos.Smooth <- function(ii, omegas, epsilons, s) {
    .Call(`_bayesEL_evalPsosSmooth`, ii, omegas, epsilons, s)
}

.logEL.smooth <- function(omegas, epsilons, deltas, s) {
    .Call(`_bayesEL_logELSmooth`, omegas, epsilons, deltas, s)
}

.evalWeights.smooth <- function(deltas, omegas, epsilons, s) {
    .Call(`_bayesEL_evalWeightsSmooth`, deltas, omegas, epsilons, s)
}

.omega.hat.EM.smooth <- function(omegasInit, G, deltas, epsilons, s, maxIter, relTol, absTol, verbose) {
    .Call(`_bayesEL_omegaHatEMSmooth`, omegasInit, G, deltas, epsilons, s, maxIter, relTol, absTol, verbose)
}

.lambdaNR <- function(G, maxIter, relTol, verbose) {
    .Call(`_bayesEL_lambdaNR`, G, maxIter, relTol, verbose)
}

.omega.hat <- function(G, lambda) {
    .Call(`_bayesEL_omegaHat`, G, lambda)
}

.logEL <- function(omegas) {
    .Call(`_bayesEL_logEL`, omegas)
}

.MeanReg_evalG <- function(y, X, beta) {
    .Call(`_bayesEL_MeanReg_evalG`, y, X, beta)
}

.MeanRegLS_evalG <- function(y, X, Z, beta, gamma, sig2) {
    .Call(`_bayesEL_MeanRegLS_evalG`, y, X, Z, beta, gamma, sig2)
}

.MeanReg_post <- function(y, X, nsamples, nburn, BetaInit, MwgSd, RvDoMcmc, maxIter = 100L, relTol = 1e-7) {
    .Call(`_bayesEL_MeanReg_post`, y, X, nsamples, nburn, BetaInit, MwgSd, RvDoMcmc, maxIter, relTol)
}

.MeanReg_post_adapt <- function(y, X, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, maxIter = 100L, relTol = 1e-7) {
    .Call(`_bayesEL_MeanReg_post_adapt`, y, X, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, maxIter, relTol)
}

.MeanRegLS_post <- function(y, X, Z, nsamples, nburn, betaInit, gammaInit, sig2Init, mwgSd, rvDoMcmc, maxIter = 100L, relTol = 1e-7) {
    .Call(`_bayesEL_MeanRegLS_post`, y, X, Z, nsamples, nburn, betaInit, gammaInit, sig2Init, mwgSd, rvDoMcmc, maxIter, relTol)
}

.MeanRegLS_post_adapt <- function(y, X, Z, nsamples, nburn, betaInit, gammaInit, sig2Init, mwgSd, rvDoMcmc, maxIter = 100L, relTol = 1e-7) {
    .Call(`_bayesEL_MeanRegLS_post_adapt`, y, X, Z, nsamples, nburn, betaInit, gammaInit, sig2Init, mwgSd, rvDoMcmc, maxIter, relTol)
}

.MeanRegCens_post <- function(omegasInit, y, X, deltas, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, doAdapt, maxIter = 100L, relTol = 1e-7, absTol = 1e-3) {
    .Call(`_bayesEL_MeanRegCens_post`, omegasInit, y, X, deltas, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, doAdapt, maxIter, relTol, absTol)
}

.MeanRegCens_post_adapt <- function(omegasInit, y, X, deltas, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, doAdapt, maxIter = 100L, relTol = 1e-7, absTol = 1e-3) {
    .Call(`_bayesEL_MeanRegCens_post_adapt`, omegasInit, y, X, deltas, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, doAdapt, maxIter, relTol, absTol)
}

.MeanRegCensLS_post_adapt <- function(omegasInit, y, X, Z, deltas, nsamples, nburn, betaInit, gammaInit, sig2Init, mwgSd, rvDoMcmc, doAdapt, maxIter = 100L, relTol = 1e-7, absTol = 1e-3) {
    .Call(`_bayesEL_MeanRegCensLS_post_adapt`, omegasInit, y, X, Z, deltas, nsamples, nburn, betaInit, gammaInit, sig2Init, mwgSd, rvDoMcmc, doAdapt, maxIter, relTol, absTol)
}

.QuantReg_evalG <- function(y, X, alphaArr, beta) {
    .Call(`_bayesEL_QuantReg_evalG`, y, X, alphaArr, beta)
}

.QuantRegLS_evalG <- function(y, X, Z, alphaArr, beta, gamma, sig2, Nu) {
    .Call(`_bayesEL_QuantRegLS_evalG`, y, X, Z, alphaArr, beta, gamma, sig2, Nu)
}

.QuantReg_post <- function(y, X, alphaArr, nsamples, nburn, BetaInit, MwgSds, RvDoMcmc, maxIter = 100L, relTol = 1e-7) {
    .Call(`_bayesEL_QuantReg_post`, y, X, alphaArr, nsamples, nburn, BetaInit, MwgSds, RvDoMcmc, maxIter, relTol)
}

.QuantReg_post_adapt <- function(y, X, alphaArr, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, maxIter = 100L, relTol = 1e-7) {
    .Call(`_bayesEL_QuantReg_post_adapt`, y, X, alphaArr, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, maxIter, relTol)
}

.QuantRegLS_post <- function(y, X, Z, alphaArr, nsamples, nburn, betaInit, gammaInit, sig2Init, nuInit, mwgSds, rvDoMcmc, maxIter = 100L, relTol = 1e-7) {
    .Call(`_bayesEL_QuantRegLS_post`, y, X, Z, alphaArr, nsamples, nburn, betaInit, gammaInit, sig2Init, nuInit, mwgSds, rvDoMcmc, maxIter, relTol)
}

.QuantRegLS_post_adapt <- function(y, X, Z, alphaArr, nsamples, nburn, betaInit, gammaInit, sig2Init, nuInit, mwgSd, rvDoMcmc, maxIter = 100L, relTol = 1e-7) {
    .Call(`_bayesEL_QuantRegLS_post_adapt`, y, X, Z, alphaArr, nsamples, nburn, betaInit, gammaInit, sig2Init, nuInit, mwgSd, rvDoMcmc, maxIter, relTol)
}

.QuantRegCens_post <- function(omegasInit, y, X, deltas, alphaArr, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, maxIter = 100L, relTol = 1e-7, absTol = 1e-3) {
    .Call(`_bayesEL_QuantRegCens_post`, omegasInit, y, X, deltas, alphaArr, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, maxIter, relTol, absTol)
}

.QuantRegCens_post_adapt <- function(omegasInit, y, X, deltas, alphaArr, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, doAdapt, maxIter = 100L, relTol = 1e-7, absTol = 1e-3) {
    .Call(`_bayesEL_QuantRegCens_post_adapt`, omegasInit, y, X, deltas, alphaArr, nsamples, nburn, betaInit, mwgSd, rvDoMcmc, doAdapt, maxIter, relTol, absTol)
}

.QuantRegCensLS_post_adapt <- function(omegasInit, y, X, Z, deltas, alphaArr, nsamples, nburn, betaInit, gammaInit, sig2Init, nuInit, mwgSd, rvDoMcmc, doAdapt, maxIter = 100L, relTol = 1e-7, absTol = 1e-3) {
    .Call(`_bayesEL_QuantRegCensLS_post_adapt`, omegasInit, y, X, Z, deltas, alphaArr, nsamples, nburn, betaInit, gammaInit, sig2Init, nuInit, mwgSd, rvDoMcmc, doAdapt, maxIter, relTol, absTol)
}

